### ISSUE TITLE
raw_data results mismatch with figure

### ISSUE THREAD

**Issue by cpwan** [ray-project/llmperf-leaderboard#15]
Hi there,
I found that the results in raw_data file does not match with the table and figure in the readme.

For example, the output token throughput for anyscale 70b.

https://github.com/ray-project/llmperf-leaderboard/blob/27aa9b6a6c4282f6d5599b9199fbb57256a2dcd8/raw_data/summary/anyscale_70b.json#L46

https://github.com/ray-project/llmperf-leaderboard/blob/27aa9b6a6c4282f6d5599b9199fbb57256a2dcd8/README.md?plain=1#L56

Please advice...

**Comment by rickyyx** [comment]
Hey @cpwan - thanks for reporting. This could have been clarified better. 

Many providers batch multiple tokens in a single "token group" when reporting - thus the actual client side token throughput  is actually underestimated. 

The one reported in the readme is calculated as `num_output_tokens / request_latency_s` that goes around this issue. 

Also, the project has not been maintained due to resource, I would recommend checking https://artificialanalysis.ai/ or other more up-to-date leaderboard for a more updated perf comparison for providers.
